config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  mount SimpleDiscussion::Engine => "/forum"
  
  devise_for :users
  root to: 'jobs#index'
  resources :jobs
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/job.rb
# == Schema Information
#
# Table name: jobs
#
#  id                  :bigint           not null, primary key
#  company_name        :string
#  company_website     :string
#  compensation_range  :string
#  compensation_type   :string
#  estimated_hours     :string
#  featured            :boolean          default(FALSE)
#  featured_until      :datetime
#  headquarters        :string
#  link_to_apply       :string
#  price               :integer
#  published_at        :datetime
#  remote              :boolean          default(FALSE)
#  slug                :string
#  status              :string           default("pending")
#  title               :string
#  upsell_type         :string
#  years_of_experience :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  user_id             :bigint           not null
#
# Indexes
#
#  index_jobs_on_slug     (slug) UNIQUE
#  index_jobs_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Job < ApplicationRecord
  extend FriendlyId

  friendly_id :slug_candidates, use: [:slugged, :finders]

  # relations
  belongs_to :user
  has_rich_text :description
  has_rich_text :company_description
  has_one_attached :company_logo

  # scopes
  scope :desc, ->{ order(created_at: :desc) }
  scope :pending, -> { where(status: JOB_STATUSES[:pending]) }
  scope :published, -> { where(status: JOB_STATUSES[:published]) }
  scope :archived, -> { where(status: JOB_STATUSES[:archived]) }

  # constants
  COMPENSATION_TYPES = [
    "Contract",
    "Full-time"
  ].freeze
  
  COMPENSATION_RANGES = [
    "50,000 - 60,000",
    "60,000 - 70,000",
    "70,000 - 80,000",
    "80,000 - 90,000",
    "90,000 - 100,000",
    "100,000 - 110,000",
    "110,000 - 120,000",
    "120,000 - 130,000",
    "130,000 - 140,000",
    "140,000 - 150,000",
    "150,000 - 160,000",
    "160,000 - 170,000",
    "170,000 - 180,000",
    "180,000 - 190,000",
    "190,000 - 200,000",
    "200,000 - 210,000",
    "210,000 - 220,000",
    "220,000 - 230,000",
    "230,000 - 240,000",
    "240,000 - 250,000",
    "greather than 250,000"
  ].freeze

  YEARS_OF_EXPERIENCE_RANGES = [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "greather than 10"
  ].freeze
  
  HOURLY_RANGES = [
    "less than 10",
    "10-30",
    "30-60",
    "60-90",
    "more than 100"
  ].freeze

  JOB_STATUSES = {
    pending: "pending",
    published: "published",
    archived: "archived"
  }.freeze

  def slug_candidates
    [:title, [:title, :company_name]]
  end
  
  def pending?
    self.status == Job::JOB_STATUSES[:pending]
  end

  def published?
    self.status == Job::JOB_STATUSES[:published]
  end

  def archived?
    self.status == Job::JOB_STATUSES[:archived]
  end

  def should_generate_new_friendly_id
    if !slug?
      title_changed?
    else
      false
    end
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: %i[ show edit update destroy ]

  # GET /jobs or /jobs.json
  def index
    @jobs = Job.published.desc
  end

  # GET /jobs/1 or /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs or /jobs.json
  def create
    @job = Job.new(job_params)
    @job.user = current_user
    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: "Job was successfully created." }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1 or /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: "Job was successfully updated." }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1 or /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: "Job was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_params
      params.require(:job).permit(
        :company_name,
        :company_website,
        :company_description,
        :company_logo,
        :description,
        :compensation_range,
        :compensation_type,
        :estimated_hours,
        :headquarters,
        :link_to_apply,
        :price,
        :remote,
        :title,
        :upsell_type,
        :years_of_experience
      )
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<div class="p-10 bg-white border rounded">
  <%= form_with(model: job, local: true, multipart: true) do |form| %>
    <% if job.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

        <ul>
          <% job.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="flex flex-wrap items-center justify-between">
      <div>
        <%= form.label :company_logo, class: "label" %>
        <%= form.file_field :company_logo %>
      </div>
      <% if form.object.company_logo.attached? %>
        <%= image_tag form.object.company_logo, class: "w-24 h-auto" %>
      <% end %>
    </div>

    <div class="input-group">
      <%= form.label :title, class: "label" %>
      <%= form.text_field :title, class: "input" %>
    </div>

    <div class="grid grid-cols-1 gap-6 lg:grid-cols-2 input-group">
      <div class="lg:col-span-1">
        <%= form.label :link_to_apply, class: "label" %>
        <%= form.text_field :link_to_apply, class: "input" %>
      </div>
      <div class="lg:col-span-1">
        <%= form.label :headquarters, class: "label" %>
        <%= form.text_field :headquarters, class: "input" %>
      </div>
    </div>

    <div class="input-group">
      <%= form.label :description, class: "label" %>
      <%= form.rich_text_area :description, class: "input" %>
    </div>

    <div class="grid grid-cols-1 gap-6 lg:grid-cols-2 input-group">
      <div class="lg:col-span-1">
        <%= form.label :company_name, class: "label" %>
        <%= form.text_field :company_name, class: "input" %>
      </div>

      <div class="lg:col-span-1">
        <%= form.label :company_website, class: "label" %>
        <%= form.text_field :company_website, class: "input" %>
      </div>
    </div>

    <div class="input-group">
      <%= form.label :company_description, class: "label" %>
      <%= form.rich_text_area :company_description, class: "input" %>
    </div>

    <div class="flex flex-wrap lg:flex-no-wrap items-center justify-start input-group">
      <div class="w-full mb-6 lg:pr-4 lg:w-1/3 lg:mb-0">
        <%= form.label :compensation_type, class: "label" %>
        <div class="relative">
          <%= form.select :compensation_type, options_for_select(Job::COMPENSATION_TYPES, form.object.compensation_type), {prompt: "Select one"}, {class: "select"} %>
          <%= select_arrow %>
        </div>
      </div>

      <div class="lg:px-2 w-full mb-6 lg:w-auto lg:mb-0">
        <%= form.label :compensation_range, class: "label" %>
        <%= form.text_field :compensation_range, class: "input" %>
      </div>

      <div class="lg:pl-4 w-full lg:w-auto">
        <%= form.label :estimated_hours, class: "label" %>
        <%= form.text_field :estimated_hours, class: "input" %>
      </div>
    </div>

    <div class="lg:pr-4 lg:w-1/3 input-group">
      <%= form.label :years_of_experience, class: "label" %>
      <%= form.text_field :years_of_experience, class: "input" %>
    </div>

    <div class="lg:w-1/2 input-group input-checkbox">
      <%= form.check_box :remote, class: "input" %>
      <%= form.label :remote, "Is this a remote only role?", class: "label" %>
    </div>

    <div class="actions">
      <%= form.submit class: "btn btn-green" %>
    </div>
  <% end %>
</div>

app/views/jobs/_job.html.erb
<div class="relative">
  <%= link_to job, class: "border-2 border-black rounded-lg py-6 lg:px-12 px-6 mb-4 block transition ease-in-out duration-300 hover:shadow-lg group" do %>
    <% if job.company_logo.attached? %>
      <div class="absolute top-0 left-0 transition duration-300 ease-in-out transform rounded-full w-16 h-16 mt-8 -ml-8 group-hover:-rotate-5 group-hover:scale-105 hover:shadow-lg">
        <%= image_tag job.company_logo.variant(resize_to_fit: [200, 200]), class: "w-16 h-16 object-cover border border-black rounded-full" %>
      </div>
    <% end %>

    <div class="flex items-center">
      <p class="text-gray-700"><%= job.company_name %></p>
      <% if job.featured? %>
        <span class="ml-2 px-2 bg-yellow-500 text-black uppercase text-xs tracking-wide font-bold rounded-lg">Featured</span>
      <% end %>
    </div>

    <h3 class="font-black text-xl"><%= job.title %></h3>

    <p class="mb-1 text-sm leading-tight text-gray-700">
      <%= job.compensation_type %> <span class="px-px text-gray-600">&bull;</span>
      <% if job.compensation_type.downcase == "contract" %>
        <%= job.estimated_hours %> hours
      <% else %>
        <%= number_to_currency(job.compensation_range) %> <span class="px-px text-gray-600">&bull;</span> <%= pluralize(job.years_of_experience, 'year') %> of experience
      <% end %>
    </p>

    <p class="text-sm leading-tight text-gray-700">
      <% if job.remote? %>
        Remote,
      <% end %>
      <%= job.headquarters %>
    </p>

  <% end %>

  <% if admin? %>
    <div class="absolute top-0 right-0 mt-4 mr-4">
      <%= link_to 'Edit', edit_job_path(job), class: "underline mr-1" %>
      <%= link_to 'Delete', job, method: :delete, data: { confirm: 'Are you sure?' }, class: "underline" %>
    </div>
  <% end %>
</div>

app/views/jobs/edit.html.erb
<div class="max-w-4xl mx-auto">
  <h1 class="my-4 text-2xl font-black leading-tight text-center lg:text-3xl">Edit your job <%= @job.title %> </h1>
  <%= render 'form', job: @job %>
</div>

app/views/jobs/index.html.erb
<%= content_for :hero do %>
  <div class="py-24 mb-16 bg-red-600 text-white">
    <div class="container mx-auto flex flex-wrap justify-center text-center">
      <h1 class="text-4xl lg:text-6xl font-black leading-tight">Find a Ruby on Rails Developer</h1>
      <p class="w-full text-lg text-red-100">The number one resource for Ruby on Rails developers</p>
      <div class="flex items-center mt-6 mb-3">
        <%= link_to "Find a developer", "#", class: "btn btn-white btn-outline py-3 px-6 lg:mr-2" %>
        <%= link_to "Find a job", jobs_path(anchor: "jobs-index"), class: "btn btn-white py-3 px-6 lg:ml-2" %>
      </div>
      <p class="w-full">or find developer friends in the <%= link_to "community", "#", class: "underline" %></p>
    </div>
  </div>
<% end %>

<div class="container mx-auto px-0 lg:px-48 mb-24">
  <%= render @jobs %>
</div>

app/views/jobs/new.html.erb
<div class="flex items-center justify-center pt-8 ">
  <%= link_to root_path, class:"link text-xl tracking-tight font-semibold group text-red-600 hover:text-red-700 transition ease-in-out flex items-center justify-start" do %>
    <%= render_svg "icons/railsdevs-mark", title: "RailsDevs", styles: "fill-current w-8 h-8 text-red-600 group-hover:text-red-700" %>
    <span class="ml-2 text-2xl font-black text-black">RailsDevs</span>
  <% end %>
</div>
<div data-controller="jobs">
  <div data-jobs-target="mount"></div>
</div>

app/views/jobs/show.html.erb
<div class="container mx-auto px-4 lg:px-24 my-10 mb-24">

  <div class="flex flex-wrap items-center justify-between border-b lg:border-0">
    <%= link_to root_path, class:"mb-4 inline-flex items-center justify-start group" do %>
      <%= render_svg "icons/chevron-left", styles: "fill-current w-5 h-5 text-gray-500 group-hover:text-red-600" %>
      <p class="text-gray-600 text-sm group-hover:text-red-700">Back to all jobs</p>
    <% end %>
  </div>

  <div class="grid grid-cols-1 gap-16 pt-6 lg:grid-cols-12">
    <div class="lg:col-span-8">
      <%= link_to @job.company_name, @job.company_website, class: "text-base text-gray-600 hover:text-red-500" %>

      <h1 class="mb-2 text-3xl font-black leading-tight lg:text-4xl"><%= @job.title %></h1>

      <p class="pb-3 mb-3 leading-tight text-gray-700 border-b">
        <%= @job.compensation_type %> <span class="px-px text-gray-600">&bull;</span>
        <% if @job.compensation_type.downcase == "contract" %>
          <%= @job.estimated_hours %> hours
        <% else %>
          <%= number_to_currency(@job.compensation_range) %> <span class="px-px text-gray-600">&bull;</span> <%= pluralize(@job.years_of_experience, 'year') %> of experience
        <% end %>
      </p>

      <h3 class="text-sm font-bold uppercase tracking-wider text-gray-800 mb-2">About the role</h3>
      <div class="prose prose-lg">
        <%= @job.description %>
      </div>

      <%= @job.remote %>

      <h3 class="text-sm font-bold uppercase tracking-wider text-gray-800 mt-10 mb-2">About the company</h3>
      <div class="mb-6 prose prose-lg">
        <%= @job.company_description %>
      </div>

      <%= link_to 'Apply for this role', @job.link_to_apply, class: "btn btn-red px-10 py-3" %>

      <% if author_of(@job) || admin? %>
        <%= link_to 'Edit this job', edit_job_path(@job), class: "ml-2 block mt-6" %>
      <% end %>
    </div>

    <div class="mb-10 lg:col-span-4 text-center">
      <div class="p-6 bg-white border-2 border-black rounded-lg shadow-sm sticky top-0 mt-6 text-gray-700">
        <% if @job.company_logo.attached? %>
          <div class="flex justify-center">
            <div class="w-16 h-16 my-3 text-center">
              <%= image_tag @job.company_logo.variant(resize_to_fit: [200, 200]), class: "flex-shrink-0 rounded-full object-cover object-center w-full h-16 border border-black" %>
            </div>
          </div>
        <% end %>
        <p><%= link_to @job.company_name, @job.company_website, class: "text-base text-gray-600 hover:text-red-500" %></p>
        <p class="lext-xl font-black text-gray-800 lg:px-4 leading-tight mb-2"><%= @job.title %></p>
        <p class="pb-3 mb-3 leading-tight text-sm text-gray-700 border-b">
          <%= @job.compensation_type %> <span class="px-px text-gray-600">&bull;</span>
          <% if @job.compensation_type.downcase == "contract" %>
            <%= @job.estimated_hours %> hours <br>
          <% else %>
            <%= number_to_currency(@job.compensation_range) %> <br> <%= pluralize(@job.years_of_experience, 'year') %> of experience
          <% end %>
        </p>
        <%= link_to 'Apply for this role', @job.link_to_apply, class: "btn btn-red px-10 py-3" %>
      </div>
    </div>
  </div>
</div>